/**
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.
 *
 * OpenAPI spec version: 17.6.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package techprague.nodes.dk.data.apis

import retrofit2.Call
import retrofit2.http.GET
import retrofit2.http.Query
import java.math.BigDecimal

interface FeedApi {

    /**
     * GET /feed
     * Get streaming feed of latest matches as newline-delimited JSON
     * @param seqNum Return only matches after this sequence number. If not provided, returns a stream starting at the current time. (optional)
     * @param gameMode Filter to only matches in this game mode (optional)
     * @param leagueid Filter to only matches in this league (optional)
     * @param includedAccountId Filter to only matches with this account_id participating (optional)
     * @return Call&lt;Array&lt;Any&gt;&gt;
     */
    @GET("/feed")
    fun feedGet(
        @Query("seq_num") seqNum: BigDecimal,
        @Query("game_mode") gameMode: BigDecimal,
        @Query("leagueid") leagueid: BigDecimal,
        @Query("included_account_id") includedAccountId: BigDecimal
    ): Call<Array<Any>>
}
