/**
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.
 *
 * OpenAPI spec version: 17.6.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package techprague.nodes.dk.data.models

/**
 *
 * @param match_id match_id
 * @param start_time start_time
 * @param hero_id The ID value of the hero played
 * @param score score
 */
data class Inline_response_200_30(
    /* match_id */
    val match_id: Int? = null,

    /* start_time */
    val start_time: Int? = null,

    /* The ID value of the hero played */
    val hero_id: Int? = null,

    /* score */
    val score: java.math.BigDecimal? = null
)
