/**
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.
 *
 * OpenAPI spec version: 17.6.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package techprague.nodes.dk.data.models

/**
 *
 * @param account_id account_id
 * @param match_id match_id
 * @param solo_competitive_rank solo_competitive_rank
 * @param competitive_rank competitive_rank
 */
data class Inline_response_200_12(
    /* account_id */
    val account_id: Int? = null,

    /* match_id */
    val match_id: Int? = null,

    /* solo_competitive_rank */
    val solo_competitive_rank: Int? = null,

    /* competitive_rank */
    val competitive_rank: Int? = null
)
