/**
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.
 *
 * OpenAPI spec version: 17.6.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package techprague.nodes.dk.data.models

/**
 *
 * @param match_id Used to identify individual matches, e.g. 3703866531
 * @param duration Length of the match
 * @param start_time Unix timestamp of when the match began
 * @param radiant_team_id The Radiant's team_id
 * @param radiant_name The Radiant's team name
 * @param dire_team_id The Dire's team_id
 * @param dire_name The Dire's team name
 * @param leagueid Identifier for the league the match took place in
 * @param league_name Name of league the match took place in
 * @param series_id Identifier for the series of the match
 * @param series_type Type of series the match was
 * @param radiant_score Number of kills the Radiant team had when the match ended
 * @param dire_score Number of kills the Dire team had when the match ended
 * @param radiant_win Whether or not the Radiant won the match
 * @param radiant Whether the team/player/hero was on Radiant
 */
data class Inline_response_200_14(
    /* Used to identify individual matches, e.g. 3703866531 */
    val match_id: Int? = null,

    /* Length of the match */
    val duration: Int? = null,

    /* Unix timestamp of when the match began */
    val start_time: Int? = null,

    /* The Radiant's team_id */
    val radiant_team_id: Int? = null,

    /* The Radiant's team name */
    val radiant_name: String? = null,

    /* The Dire's team_id */
    val dire_team_id: Int? = null,

    /* The Dire's team name */
    val dire_name: String? = null,

    /* Identifier for the league the match took place in */
    val leagueid: Int? = null,

    /* Name of league the match took place in */
    val league_name: String? = null,

    /* Identifier for the series of the match */
    val series_id: Int? = null,

    /* Type of series the match was */
    val series_type: Int? = null,

    /* Number of kills the Radiant team had when the match ended */
    val radiant_score: Int? = null,

    /* Number of kills the Dire team had when the match ended */
    val dire_score: Int? = null,

    /* Whether or not the Radiant won the match */
    val radiant_win: Boolean? = null,

    /* Whether the team/player/hero was on Radiant */
    val radiant: Boolean? = null
)
