/**
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.
 *
 * OpenAPI spec version: 17.6.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package techprague.nodes.dk.data.models

/**
 * rankings
 * @param account_id account_id
 * @param score score
 * @param steamid steamid
 * @param avatar avatar
 * @param avatarmedium avatarmedium
 * @param avatarfull avatarfull
 * @param profileurl profileurl
 * @param personaname personaname
 * @param cheese cheese
 * @param fh_unavailable fh_unavailable
 * @param loccountrycode loccountrycode
 * @param rank_tier rank_tier
 */
data class Inline_response_200_19_rankings(
    /* account_id */
    val account_id: Int? = null,

    /* score */
    val score: String? = null,

    /* steamid */
    val steamid: String? = null,

    /* avatar */
    val avatar: String? = null,

    /* avatarmedium */
    val avatarmedium: String? = null,

    /* avatarfull */
    val avatarfull: String? = null,

    /* profileurl */
    val profileurl: String? = null,

    /* personaname */
    val personaname: String? = null,

    /* cheese */
    val cheese: Int? = null,

    /* fh_unavailable */
    val fh_unavailable: Boolean? = null,

    /* loccountrycode */
    val loccountrycode: String? = null,

    /* rank_tier */
    val rank_tier: Int? = null
)
