/**
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.
 *
 * OpenAPI spec version: 17.6.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package techprague.nodes.dk.data.models

/**
 *
 * @param scenario The scenario's name or description
 * @param is_radiant Boolean indicating whether Radiant executed this scenario
 * @param region Region the game was played in
 * @param games The number of games where this scenario occurred
 * @param wins The number of games won where this scenario occured
 */
data class Inline_response_200_33(
    /* The scenario's name or description */
    val scenario: String? = null,

    /* Boolean indicating whether Radiant executed this scenario */
    val is_radiant: Boolean? = null,

    /* Region the game was played in */
    val region: Int? = null,

    /* The number of games where this scenario occurred */
    val games: String? = null,

    /* The number of games won where this scenario occured */
    val wins: String? = null
)
