/**
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.
 *
 * OpenAPI spec version: 17.6.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package techprague.nodes.dk.data.models

/**
 *
 * @param hero_id Hero ID
 * @param item Purchased item
 * @param time Ingame time in seconds before the item was purchased
 * @param games The number of games where the hero bought this item before this time
 * @param wins The number of games won where the hero bought this item before this time
 */
data class Inline_response_200_31(
    /* Hero ID */
    val hero_id: Int? = null,

    /* Purchased item */
    val item: String? = null,

    /* Ingame time in seconds before the item was purchased */
    val time: Int? = null,

    /* The number of games where the hero bought this item before this time */
    val games: String? = null,

    /* The number of games won where the hero bought this item before this time */
    val wins: String? = null
)
