/**
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.
 *
 * OpenAPI spec version: 17.6.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package techprague.nodes.dk.data.models

/**
 * match
 * @param match_id Match ID
 * @param player_slot Which slot the player is in. 0-127 are Radiant, 128-255 are Dire
 * @param radiant_win Boolean indicating whether Radiant won the match
 * @param duration Duration of the game in seconds
 * @param game_mode Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json
 * @param lobby_type Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json
 * @param hero_id The ID value of the hero played
 * @param start_time Start time of the match in seconds elapsed since 1970
 * @param version version
 * @param kills Total kills the player had at the end of the match
 * @param deaths Total deaths the player had at the end of the match
 * @param assists Total assists the player had at the end of the match
 * @param skill Skill bracket assigned by Valve (Normal, High, Very High)
 * @param lane Integer corresponding to which lane the player laned in for the match
 * @param lane_role lane_role
 * @param is_roaming Boolean describing whether or not the player roamed
 * @param cluster cluster
 * @param leaver_status Integer describing whether or not the player left the game. 0: didn't leave. 1: left safely. 2+: Abandoned
 * @param party_size Size of the players party. If not in a party, will return 1.
 */
data class Inline_response_200_3(
    /* Match ID */
    val match_id: Int? = null,

    /* Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
    val player_slot: Int? = null,

    /* Boolean indicating whether Radiant won the match */
    val radiant_win: Boolean? = null,

    /* Duration of the game in seconds */
    val duration: Int? = null,

    /* Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json */
    val game_mode: Int? = null,

    /* Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json */
    val lobby_type: Int? = null,

    /* The ID value of the hero played */
    val hero_id: Int? = null,

    /* Start time of the match in seconds elapsed since 1970 */
    val start_time: Int? = null,

    /* version */
    val version: Int? = null,

    /* Total kills the player had at the end of the match */
    val kills: Int? = null,

    /* Total deaths the player had at the end of the match */
    val deaths: Int? = null,

    /* Total assists the player had at the end of the match */
    val assists: Int? = null,

    /* Skill bracket assigned by Valve (Normal, High, Very High) */
    val skill: Int? = null,

    /* Integer corresponding to which lane the player laned in for the match */
    val lane: Int? = null,

    /* lane_role */
    val lane_role: Int? = null,

    /* Boolean describing whether or not the player roamed */
    val is_roaming: Boolean? = null,

    /* cluster */
    val cluster: Int? = null,

    /* Integer describing whether or not the player left the game. 0: didn't leave. 1: left safely. 2+: Abandoned */
    val leaver_status: Int? = null,

    /* Size of the players party. If not in a party, will return 1. */
    val party_size: Int? = null
)
