/**
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.
 *
 * OpenAPI spec version: 17.6.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package techprague.nodes.dk.data.models

/**
 *
 * @param leaver_status Integer describing whether or not the player left the game. 0: didn't leave. 1: left safely. 2+: Abandoned
 * @param game_mode Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json
 * @param lobby_type Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json
 * @param lane_role lane_role
 * @param region Integer corresponding to the region the game was played on
 * @param patch patch
 */
data class Inline_response_200_9(
    /* Integer describing whether or not the player left the game. 0: didn't leave. 1: left safely. 2+: Abandoned */
    val leaver_status: Any? = null,

    /* Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json */
    val game_mode: Any? = null,

    /* Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json */
    val lobby_type: Any? = null,

    /* lane_role */
    val lane_role: Any? = null,

    /* Integer corresponding to the region the game was played on */
    val region: Any? = null,

    /* patch */
    val patch: Any? = null
)
